### ISSUE TITLE
Version mismatch after upgrade.

### ISSUE THREAD

**Issue by Guglio95** [QuantumObject/docker-zoneminder#37]
Hi,
I'had an old image running zoneMinder, i just pulled the new one and re-launched system and just got zoneMinder stopped with this error on web gui:
"Version mismatch, system is version 1.31.1, database is 1.29.1, Please run zmupdate.pl to update".

So I went into the container and tried to run:
`zmupdate.pl `
or
`zmupdate.pl --user=zmuser --pass=zmpass`
or
`zmupdate.pl --user=root --pass=mysqlpsswd`

But I always get the same error:

DBD::mysql::db do failed: Access denied for user 'zmuser'@'localhost' to database 'zm' at /usr/share/perl5/ZoneMinder/Config.pm line 214, <STDIN> line 2.
Can't lock Config table: Access denied for user 'zmuser'@'localhost' to database 'zm' at /usr/bin/zmupdate.pl line 464.

I've tried to run:
`mysql -u zmuser --pass=zmpass`
And it actually logs in... do you know how to fix this issue?

**Comment by Guglio95** [comment]
Well, just managed to solve it:
As you can see in pre-conf.sh, the zm user lacks the support for locking a table, it's just matter of adding it:

`mysql -e "grant select,insert,update,delete,create,alter,lock tables on zm.* to 'zmuser'@localhost identified by 'zmpass';" -u root -pmysqlpsswd`

Then running `zmupdate.pl` will result in:
**Database upgrade to version 1.31.1 successful.**

**Comment by angelrr7702** [comment]
I update to new version , hope that fix the problem you have ... let me know if work now ...

sincerely
Angel  Rodriguez

**Comment by Guglio95** [comment]
Perfect :+1:

**Comment by mgscreativa** [comment]
No luck!

> Unable to connect to ZM db.SQLSTATE[HY000] [1698] Access denied for user 'zmuser'@'localhost'

```
#docker-compose up -d
version: '2'
services:
    web:
        image: 'quantumobject/docker-zoneminder:latest'
        restart: always
        hostname: 'zoneminder.mgscreativa.com.ar'
        container_name: zoneminder
        build:
            context: .
            shm_size: '4096m'
        environment:
            - TZ='America/Buenos_Aires'
        extra_hosts:
            - 'lucas.mgscreativa.com.ar:10.0.0.77'
        ports:
            - '380:80'
        volumes:
            - '/media/data/zoneminder/mysql:/var/lib/mysql'
            - '/media/data/zoneminder/zoneminder:/var/cache/zoneminder'
```
