### ISSUE TITLE
simple docker-composy.yml script

### ISSUE THREAD

**Issue by nor500** [QuantumObject/docker-zoneminder#49]
I was trying to convert your basic docker run script into a docker-compose script with the following content:
##############
version: '3.2'

services:
  db:
    image: mysql/mysql-server:5.7
    hostname: db
    networks:
       net:
    environment:
      - TZ=America/New_York
      - MYSQL_USER=zmuser
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - MYSQL_ROOT_PASSWORD=mysqlpsswd
      - MYSQL_ROOT_HOST=%
    container_name: db

  web:
   depends_on:
     - db
   image: quantumobject/docker-zoneminder
   networks:
       net:
   ports:
     - 9520:80
   restart: always
   environment:
      - ZM_DB_HOST=db
      - TZ=America/New_York
   shm_size: '4096m'
   container_name: zm
  
networks:
  net:
#########

It gaves always the following error code:

*** Failed with return value: 1
zm     | Starting pre-service scritps in /etc/my_init.d
zm     | *** Running: /etc/my_init.d/startup.sh
zm     | ERROR 2003 (HY000): Can't connect to MySQL server on 'db' (111 "Connection refused")

What am I doing wrong? Can you help me! Please!
Thank you!

**Comment by phillijw** [comment]
well, for starters I think
```
networks:
net:
```

should be

```
networks:
  - net
```

**Comment by phillijw** [comment]
This is pretty much working for me but I need to solve some permissions issues still (although that has nothing to do with the compose file itself):
```
version: '3.2'

services:
  db:
    image: mysql/mysql-server:5.7
    networks:
      - net
    volumes:
      - /var/lib/docker/volumes/zoneminder/mysql/data:/var/lib/mysql
      - /var/lib/docker/volumes/zoneminder/mysql/conf:/etc/mysql:ro
    environment:
     - TZ=America/Chicago
     - MYSQL_USER=zmuser
     - MYSQL_PASSWORD=zmpass
     - MYSQL_DATABASE=zm
     - MYSQL_ROOT_PASSWORD=mysqlpsswd
     - MYSQL_ROOT_HOST=%
  web:
    image: quantumobject/docker-zoneminder
    ports:
      - "8081:80"
    networks:
      - net
    volumes:
      - /var/empty
      - /var/lib/docker/volumes/zoneminder/backups:/var/backups
      - /var/lib/docker/volumes/zoneminder/cache:/var/cache/zoneminder
      - type: tmpfs
        target: /dev/shm
    environment:
     - TZ=America/Chicago
     - VIRTUAL_HOST=zm.localhost, stream0.localhost
     - SERVICE_PORTS="8081"
     - ZM_SERVER_HOST=node.0
     - ZM_DB_HOST=db
    depends_on:
      - db
networks:
  net:
    driver: bridge

```

**Comment by rennat** [comment]
*for the next person trying this:*
I'm using ZoneMinder for a single location running all on one machine but being accessed from other machines/devices via `http://IP:PORT`.

I'm using the directory structure and mysql conf from the readme file and I started with the `docker-compose.yml` from the previous comment here. The web interface was navigable but i was getting a range of errors in the log and no video feed.
I had to drop the `VIRTUAL_HOST` and `ZM_SERVER_HOST` environment variables. Also I had to start it twice since the first time MySQL was running but still initializing when ZM started the first time.

This is currently working for me:

```
version: "3.7"
services:

  db:
    image: "mysql/mysql-server:5.7"
    environment:
      - TZ=America/Chicago
      - MYSQL_USER=zmuser
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - MYSQL_ROOT_PASSWORD=mysqlpsswd
      - MYSQL_ROOT_HOST=%
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/cache:/etc/mysql:ro"
    networks:
      - cctv

  zm:
    image: quantumobject/docker-zoneminder
    build:
      context: .
      shm_size: '2gb'
    depends_on:
      - db
    environment:
      - TZ=America/Chicago
      - ZM_DB_HOST=db
      - SERVICE_PORTS="8081"
    volumes:
      - /var/empty
      - "./backups:/var/backups"
      - "./cache:/var/cache/zoneminder"
      - type: tmpfs
        target: /dev/shm
    networks:
      - cctv
    ports:
      - "8081:80"

networks:
  cctv:
    driver: bridge
```

- ubuntu 16.04
- docker engine community version 18.09.0
