### ISSUE TITLE
How to access network camera without host network?

### ISSUE THREAD

**Issue by royduin** [QuantumObject/docker-zoneminder#70]
Finally got Zoneminder running with Docker compose:

```
version: "3.7"
services:
  zoneminder:
    container_name: zoneminder
    restart: always
    image: quantumobject/docker-zoneminder
    depends_on:
       - db
    volumes:
      - /hdd/zoneminder:/var/cache/zoneminder
      - ${USERDIR}/docker/shared:/shared
    ports:
      - 8080:80
    environment:
      - ZM_DB_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PHP_MEMORY_LIMIT=2048M
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  db:
    container_name: db
    restart: always
    image: mysql:5.7
    volumes:
      - ${USERDIR}/docker/mysql:/var/lib/mysql
      - ${USERDIR}/docker/mysql:/config
      - ${USERDIR}/docker/shared:/shared
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=zmuser
      - MYSQL_PASSWORD=zmpass
      - MYSQL_DATABASE=zm
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
```

But how can I access the IP camera (192.168.1.4) in the network of the host (192.168.1.6)? The IP camera isn't exposed to the internet. Running it with the host network isn't an option because on the host there is already something running on port 80 so I need to run Zoneminder on a different port (8080).
