### ISSUE TITLE
Cant always view recoded events

### ISSUE THREAD

**Issue by timelyfiasco** [QuantumObject/docker-zoneminder#95]
I am experiencing a problem with a flaky storage but I am not sure where to look. 

For more than a week now, I can view the recorded events but now it is not working again. 

when viewing recorded events, an error show: "The video could not be loaded, either because the server or network failed or because the format is not supported."

But I can see the file via
`ls /var/cache/zoneminder/1/2020-05-09/90210/90210-video.mp4`

 
my docker compose yml is 
```
version: '3.4'
services:
  zmweb:
    image: quantumobject/docker-zoneminder:1.34
    container_name: zm
    restart: unless-stopped
    ports:
      - 80:80   
    volumes:
      - ./volumes/zoneminder/log:/var/log/zm
      - ./volumes/zoneminder/etc_zm:/etc/zm
      - ./volumes/zoneminder/config:/config
      - "zoneminder:/var/cache/zoneminder"
      - type: tmpfs
        target: /dev/shm
    env_file:
      - ./services/zoneminder/zoneminder.env
    depends_on:
      - mariadb

volumes:
  zoneminder:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/nfs/zoneminder
```
